server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native   # 如果不配置spring.profiles.active=native就会从git读取
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiao0803/spring-cloud-config-demo/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: xiao0803                                    # git仓库的账号
          password: 786876aaa                                   # git仓库的密码
        native:
          search-locations: classpath:/config-file  # 配置本地仓库的地址    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址
